### ISSUE TITLE
Update Arm to use SparkMax absolute encoder mode

### ISSUE THREAD

**Issue by jdlanning** [frc1675/frc1675-2023#14]
The SparkMax in the 2023 season now supports directly using an absolute encoder connected to the motor. Absolute encoders are great because they do not require a home position but can instead always know where they are located.

Encoder we will use:
https://www.revrobotics.com/rev-11-1271/

Encoder breakout board to connect to motor controller:
https://www.revrobotics.com/rev-11-3326/

To code these the following objects are needed:
https://codedocs.revrobotics.com/java/com/revrobotics/cansparkmax#getAbsoluteEncoder(com.revrobotics.SparkMaxAbsoluteEncoder.Type)

We will essentially be replacing the current DutyCycleEncoder in the 2020 code with this type of encoder

**Comment by jagernet-ops** [comment]
I finished implementing a absolute encoder class. Its specified as absEncoder and through overviewing the documentation, I discovered that for the kQuadrature encoder type, we must pass the id of 2 to the class.
