### ISSUE TITLE
Simulation of odometry and field view for off robot testing

### ISSUE THREAD

**Issue by jdlanning** [frc1675/frc1675-2023#29]
It is desired to be able to test the accuracy of our various odometry handling, such as:

* Drive base internal odometry estimation based on current velocity and rotation of the modules
* April tag informed odometry resetting while driving

In order to do this we need to create an estimate of the odometry that does not rely on the actual current velocity and rotation of the modules but instead based on the desired module states. It should be possible to implement a conditional based on whether we are in simulation mode or not (wpilib had a method which tells us this state information)

**Comment by jherrmann06** [comment]
#30
