### ISSUE TITLE
Create first draft of driver and operator control mapping

### ISSUE THREAD

**Issue by jdlanning** [frc1675/frc1675-2023#36]
Propose and code an initial button binding for the our robot controls. This should include:

* Arm controls (e.g. buttons for different score positions)
* Dual intake controls (e.g. cube mode and cone mode)
* Ground Intake controls (e.g. buttons to pickup, buttons to score)

**Comment by jherrmann06** [comment]
#64

**Comment by jherrmann06** [comment]
#69
