### ISSUE TITLE
Create driver view dashboard with important info for during the match

### ISSUE THREAD

**Issue by jdlanning** [frc1675/frc1675-2023#38]
We should think through what information is important to the drive team and how to display to them in a clear way

**Comment by jherrmann06** [comment]
Should include the selector boxes for auto options, see `AutoGenerator`

**Comment by jherrmann06** [comment]
Code on main includes auto selector boxes, could also include limelight camera view.

**Comment by jdlanning** [comment]
This is basically no action needed at this time so closing the issue
