### ISSUE TITLE
Mirror displayed pose to Red side of the field

### ISSUE THREAD

**Issue by jdlanning** [frc1675/frc1675-2023#40]
Also some other code I played around with while doing some testing today was the following to correctly display on the Field2d widget when alliance is Red:

```
// Just for Field2d widget display purposes handle pose conversion 
// to the red alliance side of the field if necessary
Pose2d displayedPose = getPose();
if(DriverStation.getAlliance() == Alliance.Red){
        final double RED_ORIGIN_POS_X_METERS = 16.541748984;
        final double RED_ORIGIN_POS_Y_METERS = 8.01367968;
        final double RED_ORIGIN_ROTATION_DEG = 180.0;
        Pose2d redOrigin = new Pose2d(
                                new Translation2d(RED_ORIGIN_POS_X_METERS, RED_ORIGIN_POS_Y_METERS),
                                Rotation2d.fromDegrees(RED_ORIGIN_ROTATION_DEG)
                        );
          displayedPose = redOrigin.transformBy(
                                new Transform2d(displayedPose.getTranslation(), displayedPose.getRotation()));
}
field.setRobotPose(displayedPose);
```

Feel free to use or adapt this as you see fit in the code. It can be tested by running an auto path with Red set as the alliance

_Originally posted by @jdlanning in https://github.com/frc1675/frc1675-2023/issues/30#issuecomment-1427352152_

Useful to consider this when implementing #34 so that we can test both the red and blue use cases with limelight in the simulator. If this is implemented when working on #34 we can show an AprilTag to the limelight and we can confirm the simulated bot is displayed at the correct location on the field in all cases.

**Comment by jherrmann06** [comment]
#52
