### ISSUE TITLE
Score cone and leave community from two start positions

### ISSUE THREAD

**Issue by jdlanning** [frc1675/frc1675-2023#60]
Need to implement our base autonomous. This command will consist of the following:

1. Move from start to location where Arm can be extended (since we cannot extend when near the grid), or set start location such that we can extend
2. Extend arm
3. Move to location where we can score the cube (might be a small movement)
4. Leave the community

This is an important task as it will be our base auto until we prove we can do something more complex. This should be our goal to get working before we leave for Duluth.

The key will be to figure out how to use the PathPlanner event mapping to trigger the necessary events along the path, or we will need to separate and have a "Score" routine initially followed by a pure path.

**Comment by jherrmann06** [comment]
Opened PR with relevant code, will complete after review of #73

**Comment by jherrmann06** [comment]
Need to test

**Comment by jherrmann06** [comment]
Actually #103
