### ISSUE TITLE
Invert floor arm encoder

### ISSUE THREAD

**Issue by jherrmann06** [frc1675/frc1675-2023#65]
Currently for both arms the sensor value decreases as the arm moves up. To handle this we have inverted the motor, but ideally we would invert the encoder sensor. 

The caveat to this change is that our encoder position values might change so we need to check this before just making the change.

**Comment by jherrmann06** [comment]
I think we handled this with the continuous input for the PID

**Comment by jdlanning** [comment]
I agree we might not get around to fixing it as we did work around it and we have lots to do. But this is just to capture what is the correct what for us to handle this. If we have time maybe we get to it.

**Comment by jdlanning** [comment]
Closing now as we wont fix this before Wisconsin
