### ISSUE TITLE
Ability to auto rotate drive while controlling translation via joystick

### ISSUE THREAD

**Issue by jdlanning** [frc1675/frc1675-2023#8]
Currently the drive has ability to auto rotate to a defined position and to hold its last heading automatically. 

As a next step we want the ability to auto rotate while the driver continues to control the XY translation via the joysticks

**Comment by jherrmann06** [comment]
#9

**Comment by jherrmann06** [comment]
Made some further changes (commit f77eaf149e65e1aa5e9b5c5a9d1a8ed3719994f5)
