### ISSUE TITLE
Write auto translation and rotation to scoring areas

### ISSUE THREAD

**Issue by jherrmann06** [frc1675/frc1675-2023#89]
I would recommend working on the human player auto translation (#88) before attempting this one.

Having another mini autonomous command which aligned the robot with the scoring area would be invaluable. Use apriltags / pose estimate to accomplish this. 

The command should have some way of translating between scoring locations, as the vision will not always lock on to the desired scoring station right away. There are many other considerations for this command, I think the programming team will discuss it before anyone starts to work on it

**Comment by jdlanning** [comment]
#95
